{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aad-finout-sync.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aad-finout-sync.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
