apiVersion: v1
kind: Service
metadata:
  name: aad-finout-sync
  namespace: $(kubernetes-namespace)
  labels:
    scrape-service-metrics: "true"
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    app: aad-finout-sync