name: aadfinoutsync deploy

on:
  push:
    paths:
      - 'k8s/**'
      - '.github/workflows/deploy.yml'
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      deploy:
        default: false
        required: false
        type: boolean
        description: "Trigger deploy"

jobs:
  deploy:
    name:  '01 - Linux'
    runs-on: [ubuntu-22.04]
    strategy:
      matrix:
        arch: ['x86_64']
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - run: 'echo "$KUBECONFIG" > /tmp/kubeconfig'
        shell: bash
        env:
          KUBECONFIG: ${{secrets.KUBECONFIG}}
      - uses: azure/setup-kubectl@v3
#        with:
#          version: '0.0.0' # default is latest stable
        id: install
      - name: 'Install Helm'
        uses: azure/setup-helm@v3
      - name: 'Generate manifests with Helm'
        run: |
         helm template --set managedByHelm=false prod chart -f k8s/values.yaml > k8s/deploy.yaml
      - name: 'Deploy manifests with Kubectl'
        env:
          KUBECONFIG: '/tmp/kubeconfig'
          NAMESPACE: 'aadfinoutsync'
        run: |
          kubectl apply -f k8s/deploy.yaml
